brain_two/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("todos/", include("todos.urls")),
]

todos/urls.py
from django.urls import path

from todos.views import (
    TodoListListView,
    TodoListDetailView,
    TodoListCreateView,
)

urlpatterns = [
    path("", TodoListListView.as_view(), name="todo_list_list"),
    path("<int:pk>/", TodoListDetailView.as_view(), name="todo_list_detail"),
    path("create/", TodoListCreateView.as_view(), name="todo_list_create"),
]

todos/models.py
from django.db import models


# Create your models here.
class TodoList(models.Model):
    name = models.CharField(max_length=100)
    created_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        # returns name as string,
        return self.name


class TodoItem(models.Model):
    task = models.CharField(max_length=100)
    due_date = models.DateTimeField(null=True, blank=True)
    is_completed = models.BooleanField(default=False)
    list = models.ForeignKey(
        # model we're using
        "TodoList",
        related_name="items",
        on_delete=models.CASCADE,
    )

    def __str__(self):
        # returns task as string
        return self.task

todos/views.py
from django.shortcuts import render
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView

from todos.models import TodoList
from django.urls import reverse_lazy


# Create your views here.
class TodoListListView(ListView):
    model = TodoList
    template_name = "todo_lists/list.html"


class TodoListDetailView(DetailView):
    model = TodoList
    template_name = "todo_lists/detail.html"


class TodoListCreateView(CreateView):
    model = TodoList
    template_name = "todo_lists/create.html"
    fields = ["name"]
    # redirect to detail page
    def get_success_url(self):
        return reverse_lazy("todo_list_detail", args=[self.object.id])

todos/templates/todo_lists/create.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <main>
        <div>
            <h1>Create a new list</h1>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button>Create</button>
            </form>
        </div>
    </main>
</body>

</html>

todos/templates/todo_lists/detail.html
<!DOCTYPE html>
<html lang="en">

<head>
    <title></title>
</head>

<body>
    <main>
        <div>
            <h1>{{todolist.name}}</h1>
            <h2>Tasks</h2>
            <table>
                <thead>
                    <tr>
                        <th>Task</th>
                        <th>Due Date</th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in todolist.items.all %}
                    <tr>
                        <td>{{item.task}}</td>
                        <td>{{item.due_date}}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </main>

</body>

</html>

todos/templates/todo_lists/list.html
<!DOCTYPe html>
<html lang="en">
<header>
    <title></title>
</header>

<body>
    <main>
        <div>
            <h1>MyLists</h1>
            <div>
                <p>
                    <a href="{% url 'todo_list_create' %}">Create a new list</a>
                </p>
            </div>
            <table>
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Number of Items</th>
                    </tr>
                </thead>
                <tbody>
                    {% for list in todolist_list %}
                    <tr>
                        <td>
                            <a href="{% url 'todo_list_detail' list.id %}">{{list.name}}</a>
                        </td>
                        <td>{{list.items.all|length}}</td>
                    </tr>
                    {% endfor %}
                </tbody>

            </table>
        </div>
    </main>
</body>

</html>